### PR TITLE
Another round of spellchecking

### PR DESCRIPTION
**Pull request by eriktorbjorn**
This is another round of spellchecking, and this time I actually ran a spellchecked over a bunch of files. It's not complete by any means, it's more of a "wow, I'm now thoroughly sick and tired of doing this".

As before, English isn't my first language and I'm not entirely certain I got things correct. I guess the ones I'm least certain about this time is where I changed "He think's he's ..." to "He thinks he's ..." and where I changed "awalking" to "walking". But really, feel free to revert any individual commit of this pull request.

### CODE REVIEW

**Comment by Kweepa** [comment]
"He think's he's" should definitely be "He thinks he's".
The same goes for "awalking". That should be "walking".

**Comment by eriktorbjorn** [comment]
Thanks for the confirmation and encouragement. When I started this round of spell-checking I never expected to find this many typos. And there are still games I haven't even looked at yet!

Though I do think I'm getting near the end of it, because so far the pattern seems pretty clear: The earlier games - even big ones like Trinity and A Mind Forever Voyaging - have barely any spelling errors, and when they do it's generally those tricky-to-spell words like "millennia". Dave Lebling once described Dave Anderson as a "terrible speller", but even so I could only find two in Hollywood Hijinx.

Some of the later games have a lot more typos, and many of them look more like slip-ups (e.g. "depresssion") than words you genuinely wouldn't know how to spell. I guess quality control really wasn't as strict under Activision...

**Comment by Kweepa** [comment]
There's some repeated text (when I was when I was) in Planetfall, at the end of the diary.
See https://github.com/Kweepa/planetfall-gold
Note that diary.zil is totally unused and the actual diary code is in globals.zil.

**Comment by eriktorbjorn** [comment]
> There's some repeated text (when I was when I was) in Planetfall, at the end of the diary.
> See https://github.com/Kweepa/planetfall-gold
> Note that diary.zil is totally unused and the actual diary code is in globals.zil.

Thanks, I'll add - or rather, remove - that. I checked with the paper version included with the original release, and the text was correct there.

**Comment by eriktorbjorn** [comment]
Other words I'm a bit uncertain of is the "almostly" I changed to "almost" in The Lurking Horror, and even more the "unexpectly" I changed to "unexpectingly" in Stationfall. (At first I considered "unexpectedly", but the more I thought about it the less sense it made to me.)

**Comment by Kweepa** [comment]
"Almost" is correct.
"Unexpectingly" is not a common word. I see where you're coming from, but I'd go with "unexpectedly", even though it doesn't as clearly indicate that it's the ostrich that wasn't expecting the event.

**Comment by eriktorbjorn** [comment]
Well, I guess "unexpectingly" was accepted before I could do anything further. Alex, what are your thoughts about it?

**Comment by AlexProudfoot** [comment]
Oops. I’d have thought unsuspectingly would be nearer the mark. I’ll change it.

**Comment by Kweepa** [comment]
We're probably getting into the weeds, but for this project I wouldn't change the word root - it seems a step too far. I probably shouldn't talk though, given what I'm doing to planetfall...

**Comment by eriktorbjorn** [comment]
Thanks. I still have a few games to go through so I've started a new branch. You can probably expect a third (and hopefully last) set of typo fixes soon.

As for the games I've gone through, I'm still not sure about the "adrenalin" in AMFV. Maybe it should be "adrenaline" after all...?

**Comment by AlexProudfoot** [comment]
@Kweepa - Thanks. You definately have a point. Here are some possibilities.
[1] no change (to something that's not a word)
[2] unexpectly -> unexpectingly (also not a word - sorry @eriktorbjorn)
[3] unexpectly -> unexpectedly (i.e. you, the player, didn't expect the ostrich to do it)
[4] unexpectly -> unsuspectingly (i.e. the ostrich didn't realise the possible consequences)
Although I like [4] better, I should probably go with [3] since @eriktorbjorn was doing spelling and typo corrections.

**Pull request merged**
